server:
  port: 8300
spring:
  rabbitmq:
    host: 81.70.213.75
    port: 5672
    username: mingrui
    password: 123456
    # 是否确认回调
    publisher-confirm-type: correlated
    # 是否返回回调
    publisher-returns: true
    virtual-host: /
    # 手动确认
    listener:
      simple:
        acknowledge-mode: manual
  jackson:
      default-property-inclusion: non_null
  elasticsearch:
    rest:
      uris: 81.70.213.75:9200
  application:
    name: search-server